# Generated by Django 3.1.4 on 2021-01-12 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipie',
            old_name='cheff',
            new_name='chef',
        ),
    ]
