# Generated by Django 3.1.4 on 2021-01-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0005_auto_20210116_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='header_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
