# Generated by Django 3.1.5 on 2021-01-16 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_auto_20210117_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
    ]
